version: "3.3"

services:
  hr-test-bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: hr-test-bot
    restart: always
    env_file: .env
    volumes:
      - .:/usr/src/hr-test-bot
    command: python main.py
    depends_on:
      - hr_postgres_db
    tty: True

#  hr-test-bot-migrate:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
#    image: hr-test-bot
#    env_file: .env
#    volumes:
#      - .:/usr/src/hr-test-bot
#    command: bash -c "alembic stamp head && alembic revision --autogenerate -m "update" && alembic upgrade head"
#    depends_on:
#      - hr_postgres_db

  hr_postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: psql_pass
    ports:
      - 5432:5432
    volumes:
      - /opt/disk/hr-test-bot/postgres:/var/lib/postgresql/data
