version: "3.3"

services:
  telebot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: perf_review__telebot
    restart: always
    env_file: .env
    container_name: perf_review__telebot
    volumes:
      - .:/usr/src/hr-test-bot
    command: python main.py
    depends_on:
      - psql
    tty: True

  migration:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: perf_review__migration
    env_file: .env
    volumes:
      - .:/usr/src/hr-test-bot
    command: bash -c "alembic stamp head && alembic revision --autogenerate -m "update" && alembic upgrade head"
    depends_on:
      - psql
    container_name: perf_review__migration

  psql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: psql_pass
    container_name: perf_review__db
