from app.tbot.services.template_forms.achievement_form_template import AchievementFormTemplate
from app.tbot.services.template_forms.achievements_form_template import AchievementsFormTemplate
from app.tbot.services.template_forms.duty_form_template import DutyFormTemplate
from app.tbot.services.template_forms.fail_form_template import FailFormTemplate
from app.tbot.services.template_forms.fails_form_template import FailsFormTemplate
from app.tbot.services.template_forms.form_template import FormTemplate
from app.tbot.services.template_forms.project_form_template import ProjectFormTemplate
from app.tbot.services.template_forms.projects_form_template import ProjectsFormTemplate
