from app.tbot.services.forms.achievement_form import AchievementForm
from app.tbot.services.forms.achievements_form import AchievementsForm
from app.tbot.services.forms.coworker_advice_form import CoworkerAdviceForm
from app.tbot.services.forms.coworker_advices_form import CoworkerAdvicesForm
from app.tbot.services.forms.duties_form import DutiesForm
from app.tbot.services.forms.duty_form import DutyForm
from app.tbot.services.forms.fail_form import FailForm
from app.tbot.services.forms.fails_form import FailsForm
from app.tbot.services.forms.list_form_review import ListFormReview
from app.tbot.services.forms.notification import Notification
from app.tbot.services.forms.project_form import ProjectForm
from app.tbot.services.forms.projects_form import ProjectsForm
from app.tbot.services.forms.review_form import ReviewForm
from app.tbot.services.forms.errors import ReviewIsNotUpped
